server:
  port: 4042
eureka:
  client:
    region: dianxin
    prefer-same-zone-eureka: true
    availability-zones:
      dianxin: zone-2,zone-1
  instance:
    metadata-map:
      zone: dianxin-zone-2
